workflows:
  Softxpert-workflow:
    name: Softxpert Pipeline
    scripts:
        - name: CICD Started
          script: echo "Welcome to CI/ CD Set up "
        - name: build Softxpert-VIPER
          script: |
            xcodebuild build \
                -workspace "Softxpert-VIPER.xcworkspace" \
                -scheme "Softxpert-VIPER" \
                CODE_SIGN_INDENTITY="" \
                CODE_SIGNING_REQUIRED=NO \
                CODE_SIGNING_ALLOWED=NO
        - name: "Run iOS tests"
          script: |
            xcode-project run-tests \
                --workspace "Softxpert-VIPER.xcworkspace" \
                --scheme "Softxpert-VIPER" \
                --device "iPhone 12"
          test_report: build/ios/test/*.xml
    publishing:
      email:
        recipients:
          - kareem.as.aboelfateh@gmail.com
